apiVersion: v1
kind: Service
metadata:
  name: stadtstack-site
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stadtstack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stadtstack.selector" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
